<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pacchetti_reykjavik">

        <xs:complexType>

            <xs:sequence>

                <xs:element
                    name="pacchetto_reykjavik"
                    maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element
                                name="id_viaggio"
                                type="xs:integer"/>

                            <xs:element
                                name="destinazione"
                                type="xs:string"/>

                            <xs:element
                                name="categoria"
                                type="xs:string"/>

                            <xs:element
                                name="data_partenza"
                                type="xs:date"/>

                            <xs:element
                                name="data_rientro"
                                type="xs:date"/>

                            <xs:element
                                name="costo"
                                type="xs:decimal"/>

                        </xs:sequence>

                        <xs:attribute
                            name="id_reykjavik"
                            type="xs:integer"
                            use="required"/>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>